
name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - uses: actions/setup-dotnet@v3
    - name: Setup .Net
      uses: actions/checkout@v2
      with:
        dotnet-version: 6.0.x
    - name: Build script
      run:
        .\PrivateBuild.ps1
